// Simple i18n translation map for RentRoad UZ.
// Keys are stable English-looking identifiers; values are translations.
// Any missing key falls back to the English entry (see AppContext `t`).

export const translations = {
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.find_cars': 'Find Cars',
    'nav.map_view': 'Map View',
    'nav.my_bookings': 'My Bookings',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.signup': 'Sign up',
    'nav.logout': 'Log out',

    // Common
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.loading': 'Loading…',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.send': 'Send',
    'common.submit': 'Submit',
    'common.total': 'Total',
    'common.status': 'Status',
    'common.reason': 'Reason',
    'common.all': 'All',

    // Profile tabs
    'profile.overview': 'Overview',
    'profile.verification': 'Verification',
    'profile.payments': 'Payment cards',
    'profile.favorites': 'Favorites',
    'profile.notifications': 'Notifications',
    'profile.settings': 'Settings',
    'profile.security': 'Security',
    'profile.help': 'Help & support',
    'profile.my_profile': 'My profile',

    // Settings
    'settings.appearance': 'Appearance',
    'settings.appearance_sub': 'Choose the theme that suits you best.',
    'settings.light': 'Light mode',
    'settings.dark': 'Dark mode',
    'settings.language': 'Language',
    'settings.language_sub': 'Set the language used across the platform.',
    'settings.currency': 'Currency',
    'settings.currency_sub': 'All prices on the platform will be shown in this currency.',

    // Bookings
    'bookings.my': 'My bookings',
    'bookings.modify': 'Modify',
    'bookings.receipt': 'Receipt',
    'bookings.cancel': 'Cancel',
    'bookings.upcoming': 'Upcoming',
    'bookings.active': 'Active',
    'bookings.completed': 'Completed',
    'bookings.cancelled': 'Cancelled',
    'bookings.pickup_date': 'Pickup date',
    'bookings.return_date': 'Return date',
    'bookings.pickup': 'Pickup',
    'bookings.dropoff': 'Drop-off',
    'bookings.id': 'Booking',

    // Find cars
    'find.title_cars_available': 'cars available',
    'find.filters': 'Filters',
    'find.reset': 'Reset',
    'find.price_per_day': 'Price per day',
    'find.car_type': 'Car type',
    'find.fuel': 'Fuel',
    'find.transmission': 'Transmission',
    'find.company': 'Company',
    'find.all_companies': 'All companies',
    'find.branch': 'Branch',
    'find.all_branches': 'All branches',
    'find.min_seats': 'Min seats',
    'find.minimum_rating': 'Minimum rating',
    'find.ac': 'Air conditioning',
    'find.no_match': 'No cars match your filters',
    'find.sort_popular': 'Most popular',
    'find.sort_low': 'Price: low to high',
    'find.sort_high': 'Price: high to low',
    'find.sort_rating': 'Best rated',
    'find.pickup_notice': 'Showing cars available for pickup in'
  },

  ru: {
    'nav.home': 'Главная',
    'nav.find_cars': 'Найти машины',
    'nav.map_view': 'Карта',
    'nav.my_bookings': 'Мои брони',
    'nav.profile': 'Профиль',
    'nav.login': 'Войти',
    'nav.signup': 'Регистрация',
    'nav.logout': 'Выйти',

    'common.back': 'Назад',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.confirm': 'Подтвердить',
    'common.close': 'Закрыть',
    'common.search': 'Поиск',
    'common.loading': 'Загрузка…',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.send': 'Отправить',
    'common.submit': 'Отправить',
    'common.total': 'Итого',
    'common.status': 'Статус',
    'common.reason': 'Причина',
    'common.all': 'Все',

    'profile.overview': 'Обзор',
    'profile.verification': 'Верификация',
    'profile.payments': 'Карты оплаты',
    'profile.favorites': 'Избранное',
    'profile.notifications': 'Уведомления',
    'profile.settings': 'Настройки',
    'profile.security': 'Безопасность',
    'profile.help': 'Помощь и поддержка',
    'profile.my_profile': 'Мой профиль',

    'settings.appearance': 'Внешний вид',
    'settings.appearance_sub': 'Выберите тему, которая вам подходит.',
    'settings.light': 'Светлая тема',
    'settings.dark': 'Тёмная тема',
    'settings.language': 'Язык',
    'settings.language_sub': 'Установите язык всей платформы.',
    'settings.currency': 'Валюта',
    'settings.currency_sub': 'Все цены будут показаны в этой валюте.',

    'bookings.my': 'Мои брони',
    'bookings.modify': 'Изменить',
    'bookings.receipt': 'Чек',
    'bookings.cancel': 'Отменить',
    'bookings.upcoming': 'Предстоящие',
    'bookings.active': 'Активные',
    'bookings.completed': 'Завершённые',
    'bookings.cancelled': 'Отменённые',
    'bookings.pickup_date': 'Дата получения',
    'bookings.return_date': 'Дата возврата',
    'bookings.pickup': 'Получение',
    'bookings.dropoff': 'Возврат',
    'bookings.id': 'Бронь',

    'find.title_cars_available': 'машин доступно',
    'find.filters': 'Фильтры',
    'find.reset': 'Сбросить',
    'find.price_per_day': 'Цена за день',
    'find.car_type': 'Тип авто',
    'find.fuel': 'Топливо',
    'find.transmission': 'Коробка',
    'find.company': 'Компания',
    'find.all_companies': 'Все компании',
    'find.branch': 'Филиал',
    'find.all_branches': 'Все филиалы',
    'find.min_seats': 'Мест не менее',
    'find.minimum_rating': 'Минимальный рейтинг',
    'find.ac': 'Кондиционер',
    'find.no_match': 'Нет машин по вашим фильтрам',
    'find.sort_popular': 'По популярности',
    'find.sort_low': 'Цена: по возрастанию',
    'find.sort_high': 'Цена: по убыванию',
    'find.sort_rating': 'По рейтингу',
    'find.pickup_notice': 'Показаны машины с получением в'
  },

  uz: {
    'nav.home': 'Bosh sahifa',
    'nav.find_cars': 'Avtomobil topish',
    'nav.map_view': 'Xarita',
    'nav.my_bookings': 'Buyurtmalarim',
    'nav.profile': 'Profil',
    'nav.login': 'Kirish',
    'nav.signup': "Ro'yxatdan o'tish",
    'nav.logout': 'Chiqish',

    'common.back': 'Orqaga',
    'common.save': 'Saqlash',
    'common.cancel': 'Bekor qilish',
    'common.confirm': 'Tasdiqlash',
    'common.close': 'Yopish',
    'common.search': 'Qidirish',
    'common.loading': 'Yuklanmoqda…',
    'common.yes': 'Ha',
    'common.no': "Yo'q",
    'common.send': 'Yuborish',
    'common.submit': 'Yuborish',
    'common.total': 'Jami',
    'common.status': 'Holat',
    'common.reason': 'Sabab',
    'common.all': 'Hammasi',

    'profile.overview': 'Umumiy',
    'profile.verification': 'Tasdiqlash',
    'profile.payments': "To'lov kartalari",
    'profile.favorites': 'Sevimlilar',
    'profile.notifications': 'Bildirishnomalar',
    'profile.settings': 'Sozlamalar',
    'profile.security': 'Xavfsizlik',
    'profile.help': "Yordam va qo'llab-quvvatlash",
    'profile.my_profile': 'Mening profilim',

    'settings.appearance': "Ko'rinish",
    'settings.appearance_sub': 'Sizga mos mavzuni tanlang.',
    'settings.light': 'Yorug‘ rejim',
    'settings.dark': 'Tungi rejim',
    'settings.language': 'Til',
    'settings.language_sub': 'Platforma tilini o‘rnating.',
    'settings.currency': 'Valyuta',
    'settings.currency_sub': 'Narxlar shu valyutada ko‘rsatiladi.',

    'bookings.my': 'Buyurtmalarim',
    'bookings.modify': "O'zgartirish",
    'bookings.receipt': 'Chek',
    'bookings.cancel': 'Bekor qilish',
    'bookings.upcoming': 'Kelgusi',
    'bookings.active': 'Faol',
    'bookings.completed': 'Tugagan',
    'bookings.cancelled': 'Bekor qilingan',
    'bookings.pickup_date': 'Olish sanasi',
    'bookings.return_date': 'Qaytarish sanasi',
    'bookings.pickup': 'Olish',
    'bookings.dropoff': 'Qaytarish',
    'bookings.id': 'Buyurtma',

    'find.title_cars_available': 'ta avtomobil mavjud',
    'find.filters': 'Filtrlar',
    'find.reset': 'Tiklash',
    'find.price_per_day': 'Kunlik narx',
    'find.car_type': 'Avtomobil turi',
    'find.fuel': 'Yoqilg‘i',
    'find.transmission': 'Uzatmalar',
    'find.company': 'Kompaniya',
    'find.all_companies': 'Barcha kompaniyalar',
    'find.branch': 'Filial',
    'find.all_branches': 'Barcha filiallar',
    'find.min_seats': 'Kamida o‘rindiq',
    'find.minimum_rating': 'Minimal reyting',
    'find.ac': 'Konditsioner',
    'find.no_match': 'Filterlaringizga mos avtomobil topilmadi',
    'find.sort_popular': 'Mashhurligi bo‘yicha',
    'find.sort_low': 'Narx: arzondan',
    'find.sort_high': 'Narx: qimmatidan',
    'find.sort_rating': 'Reyting bo‘yicha',
    'find.pickup_notice': 'Quyidagi shaharda olish uchun mavjud avtomobillar:'
  }
}
